# Generated by Django 4.2.30 on 2026-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status_enviado',
            field=models.CharField(choices=[('N', 'Não enviado'), ('E', 'Enfileirado'), ('S', 'Enviado')], db_index=True, default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='situacaoatendimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status_enviado', '-criado_em'], name='idx_atend_status_criado'),
        ),
    ]
