# Generated by Django 4.2.30 on 2026-06-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_alter_atendimento_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Status do atendimento',
                'verbose_name_plural': 'Status do atendimento',
                'db_table': 'status_atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.statusatendimento', verbose_name='Status clínico'),
        ),
    ]
