# Generated by Django 4.2.30 on 2026-06-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_statusatendimento_atendimento_status_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status_enviado',
            field=models.CharField(choices=[('N', 'Não enviado'), ('E', 'Enfileirado'), ('S', 'Enviado'), ('L', 'Limitado')], db_index=True, default='N', max_length=1),
        ),
    ]
