# Generated by Django 4.2.30 on 2026-06-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_alter_atendimento_status_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='pdf_caminho_arquivo',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='texto_extraido',
        ),
    ]
