# Generated by Django 4.2.30 on 2026-06-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('atendimentos', '0006_atendimento_pdf_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='situacaoatendimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_atendimento', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='statusatendimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_atendimento', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='situacaoatendimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statusatendimento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
