# Generated by Django 4.2.30 on 2026-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfimportlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
