# Generated by Django 4.2.30 on 2026-06-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pdf_import', '0003_pdfimportlog_nome_pdfimportlog_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimportlog',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_imports', to='empresas.empresa'),
        ),
    ]
