# Generated by Django 4.2.30 on 2026-06-22 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0005_add_envio_mensagem_tentativa_evento'),
        ('empresas', '0002_create_empresa_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='whatsapp.canalwhatsapp')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'telefone')},
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contatos', models.ManyToManyField(blank=True, related_name='segmentos', to='campanhas.contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='DestinatarioCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_snapshot', models.CharField(max_length=255)),
                ('telefone_snapshot', models.CharField(max_length=30)),
                ('variaveis_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('optout', 'Opt-out'), ('invalido', 'Inválido')], db_index=True, default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='campanhas.campanha')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatarios_campanha', to='campanhas.contato')),
                ('envio_mensagem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatario_campanha', to='whatsapp.enviomensagem')),
            ],
            options={
                'verbose_name': 'Destinatário da campanha',
                'verbose_name_plural': 'Destinatários da campanha',
                'ordering': ['campanha', 'nome_snapshot'],
            },
        ),
        migrations.AddField(
            model_name='campanha',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='campanhas.segmento'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='whatsapp.templatemensagem'),
        ),
    ]
