# Generated by Django 4.2.30 on 2026-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_enviowhatsapplog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_mensagens', models.IntegerField(default=1000, verbose_name='Limite diário de mensagens')),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configuração do sistema',
                'db_table': 'configuracao_sistema',
            },
        ),
        migrations.CreateModel(
            name='ContatoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30, unique=True)),
                ('data_bloqueio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato bloqueado',
                'verbose_name_plural': 'Contatos bloqueados (opt-out)',
                'db_table': 'contatos_bloqueados',
                'ordering': ['-data_bloqueio'],
            },
        ),
    ]
