# Generated by Django 4.2.30 on 2026-06-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('whatsapp', '0003_configuracaosistema_contatobloqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.CharField(blank=True, max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal WhatsApp',
                'verbose_name_plural': 'Canais WhatsApp',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_mensagens', models.IntegerField(default=1000, verbose_name='Limite diário de mensagens')),
                ('tamanho_lote', models.IntegerField(default=300, verbose_name='Tamanho do lote')),
                ('intervalo_segundos', models.IntegerField(default=3, verbose_name='Intervalo entre envios (segundos)')),
                ('contato_url', models.CharField(blank=True, max_length=255)),
                ('privacy_policy_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de disparo',
                'verbose_name_plural': 'Configurações de disparo',
            },
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('clinico', 'Clínico'), ('promocional', 'Promocional'), ('transacional', 'Transacional')], default='clinico', max_length=20)),
                ('corpo', models.TextField(help_text='Use {variavel} para campos dinâmicos')),
                ('variaveis_permitidas', models.JSONField(blank=True, default=list, help_text="Lista de nomes de variáveis esperadas, ex: ['nome_paciente', 'tipo_exame']")),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagem',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='contatobloqueado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_bloqueados', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='enviowhatsapplog',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contatobloqueado',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='contatobloqueado',
            constraint=models.UniqueConstraint(fields=('empresa', 'telefone'), name='uq_contato_bloqueado_empresa_telefone'),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='configuracaodisparo',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_disparo', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='canalwhatsapp',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canais_whatsapp', to='empresas.empresa'),
        ),
    ]
