# Generated by Django 4.2.30 on 2026-06-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_create_empresa_padrao'),
        ('atendimentos', '0007_atendimento_empresa_situacaoatendimento_empresa_and_more'),
        ('whatsapp', '0004_canalwhatsapp_configuracaodisparo_templatemensagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_snapshot', models.CharField(max_length=30)),
                ('conteudo_snapshot', models.TextField()),
                ('variaveis_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('agendado_para', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='whatsapp.canalwhatsapp')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_mensagem', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Envio de mensagem',
                'verbose_name_plural': 'Envios de mensagem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TentativaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('timeout', 'Timeout')], max_length=20)),
                ('resposta', models.JSONField(blank=True, default=dict)),
                ('tentado_em', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_envio', to='whatsapp.enviomensagem')),
            ],
            options={
                'verbose_name': 'Tentativa de envio',
                'verbose_name_plural': 'Tentativas de envio',
                'ordering': ['-tentado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entregue', 'Entregue'), ('lido', 'Lido'), ('falhou', 'Falhou'), ('devolvido', 'Devolvido'), ('desconhecido', 'Desconhecido')], db_index=True, default='desconhecido', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='whatsapp.enviomensagem')),
            ],
            options={
                'verbose_name': 'Evento de mensagem',
                'verbose_name_plural': 'Eventos de mensagem',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio_mensagem', to='atendimentos.atendimento')),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_envio', to='whatsapp.enviomensagem')),
            ],
            options={
                'verbose_name': 'Envio de atendimento',
                'verbose_name_plural': 'Envios de atendimento',
            },
        ),
    ]
