# Generated by Django 4.2.30 on 2026-08-14 08:33

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_create_empresa_padrao'),
        ('whatsapp', '0006_require_empresa_add_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalwhatsapp',
            name='provider',
            field=models.CharField(choices=[('WHATSAPP-BAILEYS', 'WhatsApp (QR Code) — Baileys'), ('WHATSAPP-BUSINESS', 'WhatsApp Business API — Meta (Cloud API oficial)')], default='WHATSAPP-BAILEYS', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaCloudCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID. Uma WABA pode ter vários números.', max_length=50, verbose_name='WABA ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=50, verbose_name='Phone Number ID')),
                ('meta_access_token', core.fields.EncryptedTextField(blank=True, help_text='Cifrado em repouso. Nunca exibido em texto puro pelo admin.', verbose_name='Token de acesso (Meta)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('configurado', 'Configurado'), ('erro', 'Erro')], default='pendente', max_length=12)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Preencher só se a Meta informar expiração conhecida para este token.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_meta', to='whatsapp.canalwhatsapp')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_meta', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Último usuário a definir/alterar este registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial Meta Cloud API',
                'verbose_name_plural': 'Credenciais Meta Cloud API',
                'ordering': ['empresa', 'canal'],
            },
        ),
        migrations.AddConstraint(
            model_name='metacloudcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number_id__gt', '')), fields=('phone_number_id',), name='uq_metacloudcredential_phone_number_id'),
        ),
    ]
