# Generated by Django 4.2.30 on 2026-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_canalwhatsapp_provider_metacloudcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviowhatsapplog',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enviowhatsapplog',
            name='template_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enviowhatsapplog',
            name='tipo_envio',
            field=models.CharField(choices=[('texto', 'Texto livre'), ('template', 'Template (HSM)')], default='texto', max_length=10),
        ),
    ]
