# Generated by Django 4.2.30 on 2026-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_enviowhatsapplog_external_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacloudcredential',
            name='detalhe_provisionamento',
            field=models.TextField(blank=True, help_text='Mensagem sanitizada do último provisionamento na Evolution (nunca contém o token). Preenchido por whatsapp/services/channel_provisioning.py.'),
        ),
    ]
