# Generated by Django 4.2.30 on 2026-08-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_metacloudcredential_detalhe_provisionamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatemensagem',
            options={'ordering': ['empresa', 'nome'], 'verbose_name': 'Mensagem de texto da campanha (legado/Baileys)', 'verbose_name_plural': 'Mensagens de texto da campanha (legado/Baileys)'},
        ),
    ]
